---
- name: check if a file exist
  hosts: all
  vars:
    a: /home/superheros
  tasks:
    - name: check if the file exist
      ansible.builtin.stat:
        path: "{{ a }}"
      register: file_data

    - name: print me the message if file exists
      ansible.builtin.debug:
        msg : "The file {{a}} exists"
      when: file_data.stat.exists

    - name: print me the message if file does not exists
      ansible.builtin.debug:
        msg: "The file {{a}} does not exists"
      when: not file_data.stat.exists
