---
- name: create a directory
  hosts: all
  vars:
    dir: /home/Hero
  tasks:
    - name: creating a directory using file module
      ansible.builtin.file:
        path: "{{ dir }}"
        state: directory
        owner: sha
        group: students
        mode: '744'