---
- name: create a text-file with copy module
  hosts: all
  vars:
    name: "/home/superheros.txt"
  tasks:
    - name: text file with copy module
      ansible.builtin.copy:
        dest: "{{ name }}"
        content:
          Ironman
          Captian America
          Wonder women
