---
- name: Using get-url to download the file
  hosts: all
  vars:
    myurl: "https://release.ansible.com/ansible/ansible-2.9.25.tar.gz"
    mydest: /home/devops
  tasks:
    - name: download a file
      ansible.builtin.get_url:
        url: "{{ myurl }}"
        dest: "{{ mydest }}"
        mode: '0777'
        owner: centos
        group: wheel