---
- name: "Creating the link"
  hosts: all
  vars:
    mylinks: "~/links"
    myfile: "~/file1.txt"
  tasks:
    - name: "creating link"
      ansible.builtin.file:
        src: "{{ mylinnks }}"
        dest: "{{ myfile }}"
        state: hard